# Default values for druid.

image:
  repository: apache/druid
  tag: 0.18.1
  pullPolicy: IfNotPresent
  pullSecrets: []

configMap:
  ## If false, configMap will not be applied
  ##
  enabled: true

## Define the key value pairs in the configmap
configVars:
  DRUID_XMX: 1g
  DRUID_XMS: 1g
  DRUID_MAXNEWSIZE: 250m
  DRUID_NEWSIZE: 250m
  DRUID_MAXDIRECTMEMORYSIZE: 10000m
  DRUID_USE_CONTAINER_IP: "true"
  AWS_REGION: cn-northwest-1
  druid_processing_numThreads: "3"
  druid_extensions_loadList: '["mysql-metadata-storage","druid-s3-extensions","druid-kafka-indexing-service"]'
  druid_metadata_storage_type: mysql
  druid_metadata_storage_connector_connectURI: jdbc:mysql://mysql.aws.k8s.test.lemonbox.com.cn:3306/lemonbox?useUnicode=true&characterEncoding=utf-8&useSSL=false
  druid_metadata_storage_connector_user: lemonbox
  druid_metadata_storage_connector_password: Lemonbox2020
  druid_coordinator_balancer_strategy: cachingCost
  druid_indexer_runner_javaOptsArray: '["-server", "-Xmx1g", "-Xms1g", "-XX:MaxDirectMemorySize=3g", "-Duser.timezone=UTC", "-Dfile.encoding=UTF-8", "-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager"]'
  druid_indexer_fork_property_druid_processing_buffer_sizeBytes: '268435456'
  druid_storage_type: s3
  druid_indexer_logs_type: s3
  druid_storage_bucket: lemonbox-druid
  druid_storage_baseKey: druid/segments
  druid_s3_accessKey: AKIAS6PMRAMJHUK6LUP4
  druid_s3_secretKey: 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
  druid_s3_endpoint_url: s3.cn-northwest-1.amazonaws.com.cn 
  druid_indexer_logs_s3Bucket: lemonbox-druid
  druid_indexer_logs_s3Prefix: druid/indexing-logs
  druid_emitter: noop
  druid_emitter_logging_logLevel: debug
  druid_emitter_http_recipientBaseUrl: http://druid_exporter_url:druid_exporter_port/druid
  DRUID_LOG4J: <?xml version="1.0" encoding="UTF-8" ?><Configuration status="WARN"><Appenders><Console name="Console" target="SYSTEM_OUT"><PatternLayout pattern="%d{ISO8601} %p [%t] %c - %m%n"/></Console></Appenders><Loggers><Root level="info"><AppenderRef ref="Console"/></Root><Logger name="org.apache.druid.jetty.RequestLog" additivity="false" level="DEBUG"><AppenderRef ref="Console"/></Logger></Loggers></Configuration>

gCloudStorage:
  enabled: false
  secretName: google-cloud-key

broker:
  ## If false, broker will not be installed
  ##
  enabled: true
  name: broker
  replicaCount: 1
  port: 8082
  serviceType: ClusterIP

  config:
    JAVA_OPTS: "-Xms2G -Xmx2G -XX:MaxDirectMemorySize=8g"
    # druid_monitoring_monitors: '["org.apache.druid.client.cache.CacheMonitor", "org.apache.druid.server.metrics.QueryCountStatsMonitor"]'

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - chart-example.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: 
    limits:
      cpu: 1
      memory: 8Gi
    requests:
      cpu: 1
      memory: 8Gi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  podAnnotations: {}

coordinator:
  ## If false, coordinator will not be installed
  ##
  enabled: true
  name: coordinator
  replicaCount: 1
  port: 8081
  serviceType: ClusterIP

  config:
    JAVA_OPTS: "-Xms1G -Xmx1G"
    # druid_monitoring_monitors: '["org.apache.druid.server.metrics.TaskCountStatsMonitor"]'

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - chart-example.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: 
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 2Gi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  podAnnotations: {}

overlord:
  ## If true, the separate overlord will be installed
  ##
  enabled: true
  name: overlord
  replicaCount: 1
  port: 8081
  serviceType: ClusterIP

  javaOpts: "-Xms1G -Xmx1G"

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - chart-example.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: 
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 2Gi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  podAnnotations: {}

historical:
  ## If false, historical will not be installed
  ##
  enabled: true
  name: historical
  replicaCount: 1
  port: 8083
  serviceType: ClusterIP

  config:
    JAVA_OPTS: "-Xms2G -Xmx2G -XX:MaxDirectMemorySize=8g"
    # druid_monitoring_monitors: '["org.apache.druid.client.cache.CacheMonitor", "org.apache.druid.server.metrics.HistoricalMetricsMonitor", "org.apache.druid.server.metrics.QueryCountStatsMonitor"]'

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - chart-example.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  persistence:
    enabled: false
    accessMode: ReadWriteOnce
    size: "40Gi"
    # storageClass: "ssd"

  antiAffinity: "soft"

  nodeAffinity: {}

  nodeSelector: {}

  tolerations: []

  resources: 
    limits:
      cpu: 1
      memory: 8Gi
    requests:
      cpu: 1
      memory: 8Gi

  ## (dict) If specified, apply these annotations to each master Pod
  podAnnotations: {}
  #   example: master-foo

  podDisruptionBudget:
    enabled: false
    # minAvailable: 2
    maxUnavailable: 1

  updateStrategy:
    type: RollingUpdate

middleManager:
  ## If false, middleManager will not be installed
  ##
  enabled: true
  name: middle-manager
  replicaCount: 1
  port: 8091
  serviceType: ClusterIP

  config:
    JAVA_OPTS: "-Xms1G -Xmx1G"
    # druid_monitoring_monitors: '["org.apache.druid.java.util.metrics.SysMonitor"]'

  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - chart-example.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  persistence:
    enabled: false
    accessMode: ReadWriteOnce
    size: "40Gi"
    # storageClass: "ssd"

  antiAffinity: "soft"

  nodeAffinity: {}

  nodeSelector: {}

  tolerations: []

  resources: 
    limits:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 500m
      memory: 2Gi

  ## (dict) If specified, apply these annotations to each master Pod
  podAnnotations: {}
  #   example: master-foo

  podDisruptionBudget:
    enabled: false
    # minAvailable: 2
    maxUnavailable: 1

  updateStrategy:
    type: RollingUpdate

router:
  ## If false, router will not be installed
  ##
  enabled: true
  name: router
  replicaCount: 1
  port: 8888
  serviceType: ClusterIP

  config:
    JAVA_OPTS: "-Xms1G -Xmx1G"

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - chart-example.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: 
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 2Gi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  podAnnotations: {}

# ------------------------------------------------------------------------------
# Zookeeper:
# ------------------------------------------------------------------------------

zkHosts: zk-cs.default:2181/druid

zookeeper:
  enabled: false
  ## Environmental variables to set in Zookeeper
  ##
  env:
    ## The JVM heap size to allocate to Zookeeper
    ZK_HEAP_SIZE: "512M"
  ## Configure Zookeeper headless
  headless:
    publishNotReadyAddresses: true


# ------------------------------------------------------------------------------
# MySQL:
# ------------------------------------------------------------------------------
mysql:
  enabled: false
  mysqlRootPassword: druidroot
  mysqlUser: druid
  mysqlPassword: druid
  mysqlDatabase: druid
  configurationFiles:
    mysql_collate.cnf: |-
      [mysqld]
      character-set-server=utf8
      collation-server=utf8_unicode_ci

# ------------------------------------------------------------------------------
# postgres:
# ------------------------------------------------------------------------------
postgresql:
  enabled: false
  postgresqlUsername: druid
  postgresqlPassword: druid
  postgresqlDatabase: druid
  service:
    port: 5432

# Secrets
